services:
  app:
    build: .
    ports:
      - "127.0.0.1:11600:11600"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    command: ["./system.exe", "mjai_client", "11600", "./setup_mjai.json"]
